In [1]:
import pandas as pd

## Create Series 
A series is a one-dimensional array-like object. It labels each data item. The associated array of data labels is called the index of series.

In [2]:
# Create Series with default index:
ser1 = pd.Series([5, 8, -3])
print(ser1)

0    5
1    8
2   -3
dtype: int64

In [3]:
# Create Series with assigned index:
ser2 = pd.Series([5, 8, -3], index=["a", "b", "c"])
print(ser2)

a    5
b    8
c   -3
dtype: int64

### Selection on Series

Passing **an index** - either the default or the assigned index

In [4]:
ser2['a']

5

In [5]:
ser2.iloc[0]

5

Passing **a list of indices** - either the default or the assigned indices

In [6]:
ser2[['a', 'c']]

a    5
c   -3
dtype: int64

In [7]:
ser2.iloc[[0, 2]]

a    5
c   -3
dtype: int64

Passing **a slice of default indices**

In [8]:
ser2[:2]

a    5
b    8
dtype: int64

## Create DataFrames 
A dataframe is a 2-dimentional data structure. It represents a rectangular table of data with rows and columns. Columns can be of different data types. Just like series, dataframes label the data.

In [9]:
# Create a dataframe from dictionary of lists:
dict_of_lists = {"name" : ["Nick", "Tom", "Rose"], 
                 "title" : ["Professor", "Attorney", "Physician"], 
                 "age" : [58, 45, 36]}

df1 = pd.DataFrame(dict_of_lists)
print(df1)

   name      title  age
0  Nick  Professor   58
1   Tom   Attorney   45
2  Rose  Physician   36

In [10]:
df1 = pd.DataFrame(dict_of_lists, index=["p1", "p2", "p3"])
print(df1)

    name      title  age
p1  Nick  Professor   58
p2   Tom   Attorney   45
p3  Rose  Physician   36

In [11]:
# Create a dataframe from list of lists:
list_of_lists = [["New York City", 8601186, 2019], ["Los Angeles", 4057841, 2019], ["Chicago", 2679044, 2019]] 
df2 = pd.DataFrame(list_of_lists)
print(df2)

               0        1     2
0  New York City  8601186  2019
1    Los Angeles  4057841  2019
2        Chicago  2679044  2019

In [12]:
df2 = pd.DataFrame(list_of_lists, columns=["city", "population", "year"])
print(df2)

            city  population  year
0  New York City     8601186  2019
1    Los Angeles     4057841  2019
2        Chicago     2679044  2019

### Selection on DataFrames

#### Selecting columns using standard Python dictionary notation

In [13]:
df1['age']

p1    58
p2    45
p3    36
Name: age, dtype: int64

#### Selecting rows and columns using `loc` and `iloc` methods
`loc` and `iloc` methods are used to select from rows and columns.  
`loc` method gets the rows/columns labels (assigned indices). 
`iloc` method gets the rows/columns positions starting from zero (default indices).

Selecting just rows using `iloc` method

In [14]:
df1.iloc[0]

name          Nick
title    Professor
age             58
Name: p1, dtype: object

In [15]:
df1.iloc[[0, 2]]

    name      title  age
p1  Nick  Professor   58
p3  Rose  Physician   36

In [16]:
df1.iloc[:2]

    name      title  age
p1  Nick  Professor   58
p2   Tom   Attorney   45

Selecting both rows and columns using `iloc` method

In [17]:
df1.iloc[0, 2]

58

In [18]:
df1.iloc[[0, 2], [1, 2]]

        title  age
p1  Professor   58
p3  Physician   36

In [19]:
df1.iloc[:, :2]

    name      title
p1  Nick  Professor
p2   Tom   Attorney
p3  Rose  Physician