## Manipulating dataframes in pandas
This notebook covers some useful methods for manipulating the rows of dataframes.

In [1]:
import pandas as pd

### Sorting the rows of a dataframe

In [2]:
frame = pd.DataFrame({'num':range(5), 'val':[5, 3, 9, 2, 4]}, index=list('deabc'))
print(frame)

   num  val
d    0    5
e    1    3
a    2    9
b    3    2
c    4    4

Sort the rows of a dataframe by its index values:

In [3]:
frame.sort_index()

   num  val
a    2    9
b    3    2
c    4    4
d    0    5
e    1    3

Sort the rows of a dataframe based on the values in a specified column:

In [4]:
frame.sort_values('val')

   num  val
b    3    2
e    1    3
c    4    4
d    0    5
a    2    9

`sort_index()` and `sort_values()` methods return a sorted **copy** of frame. To mutate an existing dataframe, `pandas` provides the option `inplace=True` to both methods.

In [5]:
print("The original frame is:\n", frame)

The original frame is:
    num  val
d    0    5
e    1    3
a    2    9
b    3    2
c    4    4

In [6]:
frame.sort_values('val', inplace=True)
print("The mutated sorted frame is:\n", frame)

The mutated sorted frame is:
    num  val
b    3    2
e    1    3
c    4    4
d    0    5
a    2    9

Review the documentations for [sort_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html) and [sort_values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html) methods to learn other available parameters.

The `head()` and `tail()` methods return a dataframe formed by the first few or last few rows of the dataframe, respectively.

In [7]:
frame.head(2)

   num  val
b    3    2
e    1    3

In [8]:
frame.tail(3)

   num  val
c    4    4
d    0    5
a    2    9

### Merging, joining, and concatenating the rows of two dataframes

In [9]:
# Define two simple dataframes, note dtype=object prevents converting to float during merge/join/concat
df1 = pd.DataFrame({'A':range(6), 'B':[5, 3, 6, 9, 2, 4]}, index=list('abcdef'), dtype=object)
df2 = pd.DataFrame({'C':range(4), 'D':[10, 20, 30, 40]}, index=list('abhi'), dtype=object)
print("First dataframe\n", df1)
print("Second dataframe\n", df2)

First dataframe
    A  B
a  0  5
b  1  3
c  2  6
d  3  9
e  4  2
f  5  4
Second dataframe
    C   D
a  0  10
b  1  20
h  2  30
i  3  40

#### `merge()` method
This method merges two dataframes by their common index or specified columns. By default, it acts similar to an SQL inner join; it returns a dataframe consisting of the intersection of the rows and all the columns of both dataframes. Review this [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) to learn this method's parameters.

An example of merging by their common index:

In [10]:
# merge df1 and df2 based on their common indices 
# this returns the intersection of df1 and df2 rows and all of their columns
merged1_df = df1.merge(df2, left_index=True, right_index=True)
print("Merging two dataframes by indices\n", merged1_df)

Merging two dataframes by indices
    A  B  C   D
a  0  5  0  10
b  1  3  1  20

An example of merging by specified columns:

In [11]:
# merge df1 and df2 based on their columns 'a' and 'c'
# this returns the intersection of df1 and df2 rows and all of their columns
merged2_df = df1.merge(df2, left_on='A', right_on='C')
print("Merging two dataframes by columns\n", merged2_df)

Merging two dataframes by columns
    A  B  C   D
0  0  5  0  10
1  1  3  1  20
2  2  6  2  30
3  3  9  3  40

Notice that if merging columns on columns, the dataframe indices will be ignored and disappeared.

#### `join()` method
This method joins the columns of the second dataframe with the first dataframe by their common index. By default, it acts similar to an SQL left join; it returns a dataframe consisting of  all the rows of the first dataframe with the intersecting rows from the second dataframe and all the columns from both dataframes. Review this [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html) to learn this method's parameters.

In [12]:
# join df2 with df1 based on their common indices
# this returns all the rows from df1 with the intersecting rows from df2 and all of their columns
joined_df = df1.join(df2)
print("Joining second dataframe to first\n", joined_df)

Joining second dataframe to first
    A  B    C    D
a  0  5    0   10
b  1  3    1   20
c  2  6  NaN  NaN
d  3  9  NaN  NaN
e  4  2  NaN  NaN
f  5  4  NaN  NaN

#### `concat()` method
This method concatenates two dataframes along either rows (axis=0) or columns (axis=1). By default, it acts similar to an SQL outer join. Concatenating along the rows returns all the rows of both dataframes with the union of columns, whereas, concatenating along the columns returns the union of the rows and all the columns from both dataframes. Review this [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to learn this method's parameters.

In [13]:
# concatentate df1 and df2 along their columns
# this returns the unions of rows and union of columns
concat_df = pd.concat([df1, df2], axis=1, sort=True)
print("Concatenating two dataframes\n", concat_df)

Concatenating two dataframes
      A    B    C    D
a    0    5    0   10
b    1    3    1   20
c    2    6  NaN  NaN
d    3    9  NaN  NaN
e    4    2  NaN  NaN
f    5    4  NaN  NaN
h  NaN  NaN    2   30
i  NaN  NaN    3   40